{% set name = "cmd2" %}
{% set version = "1.3.11" %}
{% set bundle = "tar.gz" %}
{% set hash = "826a288ee6d9c4ec1184e64e9566c09d3b73be8f4283c1898fa4332f1daf8dbf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  skip: true  # [py2k]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm

  run:
    - python
    - setuptools
    - pyperclip >=1.5.27
    - colorama
    - attrs
    - pyreadline  # [win]
    - wcwidth
    - contextlib2  # [py<35]
    - typing  # [py<35]

test:
  imports:
    - cmd2

about:
  home: https://github.com/python-cmd2/cmd2
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Extra features for standard library's cmd module
  dev_url: https://github.com/python-cmd2/cmd2
  doc_url: https://cmd2.readthedocs.io/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
