{% set name = "cmd2" %}
{% set version = "0.9.22" %}
{% set bundle = "tar.gz" %}
{% set hash = "ba244b07c0b465ff54a6838dc61919599141dc92de1bf00bb0a70875189155e6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  skip: True  # [py2k]
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm

  run:
    - python
    - setuptools
    - pyperclip >=1.5.27
    - colorama
    - attrs
    - pyreadline  # [win]
    - wcwidth
    - contextlib2  # [py<35]
    - typing  # [py<35]
    

test:
  imports:
    - cmd2

about:
  home: https://github.com/python-cmd2/cmd2
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: "Extra features for standard library's cmd module"
  dev_url: https://github.com/python-cmd2/cmd2
  doc_url: https://cmd2.readthedocs.io/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
