{% set name = "cmd2" %}
{% set version = "2.5.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "701118568379b4c983b99f39b812c3931be4074b1ff71d0bd5c48c15d54d4b3c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools

  run:
    - python
    - setuptools
    - attrs >=16.3.0
    - pyperclip >=1.6
    - pyreadline3  # [win]
    - wcwidth >=0.1.7

test:
  imports:
    - cmd2
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/python-cmd2/cmd2
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Extra features for standard library's cmd module
  dev_url: https://github.com/python-cmd2/cmd2
  doc_url: https://cmd2.readthedocs.io/

extra:
  recipe-maintainers:
    - anguslees
    - tschoonj
