{% set name = "cmd2" %}
{% set version = "0.8.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "4b3a9d9f305039ca94deb93e0a54ba896f12d1aae7206c6283fe02c6dbb0b7ba" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pyparsing >=2.0.1
    - pyperclip
    - six
    - pyreadline  # [win]

test:
  imports:
    - cmd2

about:
  home: https://github.com/python-cmd2/cmd2
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: "Extra features for standard library's cmd module"
  dev_url: https://github.com/python-cmd2/cmd2
  doc_url: https://cmd2.readthedocs.io/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
